#!/bin/sh

usage() {
  echo "Usage: $0 <tumblr-domain>"
  exit 0
}

if [ -z "$1" ]; then
  usage
fi

DOMAIN="$1"

DELAY='2' # sec

wget \
  -nd \
  -P "$DOMAIN" \
  -mpNHk \
  -D ".media.tumblr.com,media.tumblr.com,$DOMAIN" \
  -w "$DELAY" \
  -R "*avatar*,*\?*,*_[0-9][0-9][0-9].*" \
  "http://$DOMAIN"
