#!/usr/bin/env sh
#
# Usage:
#
# wget-memegenerator <tag>

DELAY=1 # sec

TAG="$1"

DIR="memegenerator-$TAG"

PAGES=$(wget -q -O- "http://memegenerator.net/$TAG/images/new/alltime/page/1" | grep » -B 6 | grep page | head -n 1 | tr "[<>]" " " | awk '{ print $3 }')

for PAGE in $(seq 1 $PAGES); do
  wget -q \
    -rN \
    --no-remove-listing \
    -pNHk \
    -l 1 \
    -D "memegenerator.net,cdn.meme.am" \
    --exclude-domains "blog.memegenerator.net,api.memegenerator.net,es.memegenerator.net,ru.memegenerator.net" \
    -w $DELAY \
    -nd \
    -P "$DIR" \
    -I "$TAG/,$TAG/images/,instance/,instances/" \
    -X "*/250x250/,*/400x/" \
    -R "new,alltime" \
    "http://memegenerator.net/$TAG/images/new/alltime/page/$PAGE"
done

find "$DIR" ! -name '*.jpg' -delete

zip -r "$DIR.cbz" "$DIR"

rm -rf "$DIR"
